import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  activeTab: {
    backgroundColor: "#7C5CFF",
    shadowColor: "#7C5CFF",
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 18,
  },
  activeTabText: { color: "#FFFFFF" },
  brandMark: {
    alignItems: "center",
    backgroundColor: "rgba(34, 211, 238, 0.14)",
    borderColor: "rgba(34, 211, 238, 0.28)",
    borderRadius: 16,
    borderWidth: 1,
    height: 46,
    justifyContent: "center",
    width: 46,
  },
  brandMarkText: { color: "#22D3EE", fontSize: 22, fontWeight: "900" },
  brandRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    marginBottom: 18,
    paddingHorizontal: 4,
  },
  brandSubtle: { color: "#8A94B2", fontSize: 13, fontWeight: "700", marginTop: 2 },
  button: {
    alignItems: "center",
    borderRadius: 18,
    justifyContent: "center",
    marginTop: 22,
    minHeight: 58,
    shadowColor: "#7C5CFF",
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
  },
  buttonText: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  card: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 28,
    borderWidth: 1,
    overflow: "hidden",
    padding: 24,
    shadowColor: "#000000",
    shadowOffset: { height: 22, width: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 32,
    width: "100%",
  },
  cardGlow: {
    backgroundColor: "rgba(124, 92, 255, 0.16)",
    borderRadius: 120,
    height: 180,
    position: "absolute",
    right: -80,
    top: -100,
    width: 180,
  },
  content: {
    flexGrow: 1,
    justifyContent: "center",
    padding: 24,
  },
  danger: { backgroundColor: "rgba(248, 113, 113, 0.14)", color: "#FECACA" },
  disabledButton: { opacity: 0.6 },
  eyebrow: {
    color: "#22D3EE",
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: 0,
  },
  field: { marginTop: 16 },
  input: {
    backgroundColor: "#0B0F1A",
    borderColor: "#263250",
    borderRadius: 18,
    borderWidth: 1,
    color: "#E8ECF8",
    fontSize: 17,
    minHeight: 58,
    paddingHorizontal: 16,
  },
  kicker: {
    color: "#8A94B2",
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 0,
    marginBottom: 8,
    textTransform: "uppercase",
  },
  label: {
    color: "#C9D1E8",
    fontSize: 13,
    fontWeight: "900",
    marginBottom: 8,
  },
  muted: { color: "#8A94B2", fontSize: 16, marginBottom: 16 },
  neutral: { backgroundColor: "rgba(138, 148, 178, 0.14)", color: "#C9D1E8" },
  primaryButton: { backgroundColor: "#7C5CFF" },
  screen: { backgroundColor: "#0B0F1A", flex: 1 },
  secondaryButton: { backgroundColor: "#1E2740" },
  status: {
    borderRadius: 16,
    fontSize: 14,
    fontWeight: "800",
    lineHeight: 20,
    marginTop: 14,
    overflow: "hidden",
    padding: 14,
  },
  success: { backgroundColor: "rgba(52, 211, 153, 0.14)", color: "#BBF7D0" },
  tab: {
    alignItems: "center",
    borderRadius: 18,
    flex: 1,
    justifyContent: "center",
    minHeight: 54,
  },
  tabText: { color: "#8A94B2", fontSize: 16, fontWeight: "900" },
  tabs: {
    backgroundColor: "#0B0F1A",
    borderColor: "#1E2740",
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    marginBottom: 8,
    marginTop: 8,
    padding: 6,
  },
  title: {
    color: "#E8ECF8",
    fontSize: 42,
    fontWeight: "900",
    letterSpacing: 0,
    marginBottom: 16,
  },
  warning: { backgroundColor: "rgba(251, 191, 36, 0.14)", color: "#FDE68A" },
});
