import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  activeTab: { backgroundColor: "#7C5CFF" },
  activeTabText: { color: "#FFFFFF" },
  button: {
    alignItems: "center",
    borderRadius: 12,
    justifyContent: "center",
    marginTop: 12,
    minHeight: 48,
  },
  buttonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "800" },
  card: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 16,
    borderWidth: 1,
    padding: 24,
    width: "100%",
  },
  content: { flexGrow: 1, justifyContent: "center", padding: 24 },
  danger: { backgroundColor: "rgba(248, 113, 113, 0.14)", color: "#FECACA" },
  eyebrow: { color: "#22D3EE", fontSize: 13, fontWeight: "800", marginBottom: 10 },
  input: {
    backgroundColor: "#0B0F1A",
    borderColor: "#1E2740",
    borderRadius: 12,
    borderWidth: 1,
    color: "#E8ECF8",
    fontSize: 16,
    marginTop: 12,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  muted: { color: "#8A94B2", fontSize: 16, marginBottom: 16 },
  neutral: { backgroundColor: "rgba(138, 148, 178, 0.14)", color: "#C9D1E8" },
  primaryButton: { backgroundColor: "#7C5CFF" },
  screen: { backgroundColor: "#0B0F1A", flex: 1 },
  secondaryButton: { backgroundColor: "#1E2740" },
  status: { borderRadius: 12, lineHeight: 20, marginTop: 12, padding: 12 },
  success: { backgroundColor: "rgba(52, 211, 153, 0.14)", color: "#BBF7D0" },
  tab: {
    alignItems: "center",
    borderRadius: 8,
    flex: 1,
    justifyContent: "center",
    minHeight: 44,
  },
  tabText: { color: "#8A94B2", fontWeight: "700" },
  tabs: {
    backgroundColor: "#0B0F1A",
    borderRadius: 12,
    flexDirection: "row",
    gap: 4,
    marginBottom: 4,
    padding: 4,
  },
  title: { color: "#E8ECF8", fontSize: 32, fontWeight: "800", marginBottom: 18 },
  warning: { backgroundColor: "rgba(251, 191, 36, 0.14)", color: "#FDE68A" },
});
