import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  actionButton: {
    alignItems: "center",
    borderRadius: 12,
    flex: 1,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 12,
  },
  actionText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" },
  activeItem: { borderColor: "#7C5CFF" },
  buttonText: { color: "#FFFFFF", fontSize: 14, fontWeight: "800" },
  card: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  danger: { backgroundColor: "rgba(248, 113, 113, 0.14)", color: "#FECACA" },
  empty: {
    borderColor: "#1E2740",
    borderRadius: 12,
    borderStyle: "dashed",
    borderWidth: 1,
    color: "#8A94B2",
    padding: 16,
    textAlign: "center",
  },
  eyebrow: { color: "#22D3EE", fontSize: 13, fontWeight: "800", marginBottom: 8 },
  flex: { flex: 1 },
  form: { borderBottomColor: "#1E2740", borderBottomWidth: 1, gap: 10, paddingBottom: 12 },
  header: { flexDirection: "row", gap: 12, justifyContent: "space-between" },
  inlineButton: { justifyContent: "center", minHeight: 36, paddingHorizontal: 4 },
  inlineDanger: { color: "#F87171" },
  inlineText: { color: "#22D3EE", fontWeight: "800" },
  input: {
    backgroundColor: "#0B0F1A",
    borderColor: "#1E2740",
    borderRadius: 12,
    borderWidth: 1,
    color: "#E8ECF8",
    fontSize: 15,
    minHeight: 44,
    paddingHorizontal: 12,
  },
  item: {
    backgroundColor: "#0B0F1A",
    borderColor: "#1E2740",
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  itemMain: { gap: 4 },
  itemMeta: { color: "#8A94B2", fontSize: 13 },
  itemTitle: { color: "#E8ECF8", fontSize: 16, fontWeight: "800" },
  list: { gap: 10 },
  metric: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minWidth: "45%",
    padding: 14,
  },
  metricLabel: { color: "#8A94B2", fontSize: 12, marginBottom: 4 },
  metricValue: { color: "#E8ECF8", fontSize: 26, fontWeight: "900" },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  muted: { color: "#8A94B2", fontSize: 14 },
  notice: { borderRadius: 12, lineHeight: 20, padding: 12 },
  primaryAction: { backgroundColor: "#7C5CFF" },
  row: { flexDirection: "row", gap: 10 },
  screen: { backgroundColor: "#0B0F1A", gap: 16, padding: 16, paddingBottom: 32 },
  secondaryAction: { backgroundColor: "#1E2740" },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#1E2740",
    borderRadius: 12,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 14,
  },
  sectionHeading: { color: "#E8ECF8", fontSize: 20, fontWeight: "900" },
  sectionTitle: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  segment: {
    alignItems: "center",
    borderRadius: 9,
    flex: 1,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 6,
  },
  segmentActive: { backgroundColor: "#7C5CFF" },
  segmentText: { color: "#8A94B2", fontSize: 12, fontWeight: "800" },
  segmentTextActive: { color: "#FFFFFF" },
  segments: {
    backgroundColor: "#0B0F1A",
    borderColor: "#1E2740",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    padding: 4,
  },
  title: { color: "#E8ECF8", fontSize: 30, fontWeight: "900" },
  warning: { backgroundColor: "rgba(251, 191, 36, 0.14)", color: "#FDE68A" },
});
