import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  accentMetric: { borderColor: "rgba(34, 211, 238, 0.45)" },
  actionButton: {
    alignItems: "center",
    borderRadius: 14,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  actionText: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" },
  activeItem: { borderColor: "#7C5CFF" },
  badge: {
    backgroundColor: "rgba(138, 148, 178, 0.16)",
    borderRadius: 999,
    color: "#C9D1E8",
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  bottomNav: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderWidth: 1,
    bottom: 18,
    flexDirection: "row",
    gap: 8,
    left: 16,
    padding: 6,
    position: "absolute",
    right: 16,
    shadowColor: "#000000",
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.34,
    shadowRadius: 24,
  },
  clearButton: {
    alignItems: "center",
    backgroundColor: "#1E2740",
    borderRadius: 14,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  clearText: { color: "#E8ECF8", fontWeight: "900" },
  completeItem: { borderColor: "rgba(52, 211, 153, 0.4)" },
  danger: { backgroundColor: "rgba(248, 113, 113, 0.14)", color: "#FECACA" },
  dateStack: { gap: 12 },
  disabledAction: { opacity: 0.45 },
  emptyState: {
    alignItems: "center",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderStyle: "dashed",
    borderWidth: 1,
    gap: 6,
    padding: 20,
  },
  emptyText: { color: "#8A94B2", fontSize: 13, textAlign: "center" },
  emptyTitle: { color: "#C9D1E8", fontSize: 15, fontWeight: "900", textAlign: "center" },
  eyebrow: { color: "#22D3EE", fontSize: 14, fontWeight: "900", marginBottom: 10 },
  flex: { flex: 1 },
  focusCard: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    padding: 16,
  },
  focusLabel: { color: "#22D3EE", fontSize: 12, fontWeight: "900" },
  focusMeta: { color: "#8A94B2", fontSize: 13 },
  focusTitle: { color: "#E8ECF8", fontSize: 19, fontWeight: "900" },
  form: { gap: 12 },
  hero: {
    backgroundColor: "#121829",
    borderColor: "#253453",
    borderRadius: 22,
    borderWidth: 1,
    gap: 8,
    padding: 18,
  },
  heroCopy: { color: "#C9D1E8", fontSize: 14, fontWeight: "700" },
  heroIdentity: { flex: 1, minWidth: 0 },
  heroMetaRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 14,
    justifyContent: "space-between",
  },
  heroSubcopy: { color: "#8A94B2", fontSize: 13, lineHeight: 19 },
  heroTop: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
  },
  hotBadge: { backgroundColor: "rgba(248, 113, 113, 0.16)", color: "#FECACA" },
  inlineActions: {
    borderTopColor: "#1E2740",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 18,
    paddingTop: 12,
  },
  inlineButton: { justifyContent: "center", minHeight: 36 },
  inlineDanger: { color: "#F87171" },
  inlineText: { color: "#22D3EE", fontWeight: "900" },
  input: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 14,
    borderWidth: 1,
    color: "#E8ECF8",
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  item: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  itemBody: { color: "#C9D1E8", fontSize: 14, lineHeight: 20 },
  itemMeta: { color: "#8A94B2", fontSize: 13, fontWeight: "700" },
  itemTitle: { color: "#E8ECF8", fontSize: 17, fontWeight: "900" },
  itemTop: { alignItems: "flex-start", flexDirection: "row", gap: 12 },
  list: { gap: 12 },
  logoutButton: {
    alignItems: "center",
    backgroundColor: "#1E2740",
    borderRadius: 14,
    justifyContent: "center",
    minHeight: 44,
    minWidth: 90,
    paddingHorizontal: 12,
  },
  logoutText: { color: "#E8ECF8", fontSize: 13, fontWeight: "900" },
  metric: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minWidth: "46%",
    padding: 16,
  },
  metricLabel: { color: "#8A94B2", fontSize: 12, fontWeight: "800", marginBottom: 8 },
  metricValue: { color: "#E8ECF8", fontSize: 30, fontWeight: "900" },
  metricsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  muted: { color: "#8A94B2", flexShrink: 1, fontSize: 13, fontWeight: "700", textAlign: "right" },
  navItem: {
    alignItems: "center",
    borderRadius: 13,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
  },
  navItemActive: { backgroundColor: "#7C5CFF" },
  navText: { color: "#8A94B2", fontSize: 13, fontWeight: "900" },
  navTextActive: { color: "#FFFFFF" },
  notice: { borderRadius: 14, lineHeight: 20, padding: 13 },
  panel: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  primaryAction: { backgroundColor: "#7C5CFF" },
  primaryMetric: { borderColor: "rgba(124, 92, 255, 0.55)" },
  progressFill: { backgroundColor: "#34D399", borderRadius: 999, height: 7 },
  progressText: { color: "#34D399", fontSize: 15, fontWeight: "900" },
  progressTrack: { backgroundColor: "#0B0F1A", borderRadius: 999, height: 7, overflow: "hidden" },
  quickActions: { flexDirection: "row", gap: 12 },
  root: { backgroundColor: "#0B0F1A", flex: 1 },
  row: { flexDirection: "row", gap: 10 },
  screen: { gap: 16, padding: 16, paddingBottom: 132 },
  searchRow: { flexDirection: "row", gap: 10 },
  secondaryAction: { backgroundColor: "#253453" },
  sectionHeading: { color: "#E8ECF8", flex: 1, fontSize: 22, fontWeight: "900" },
  sectionTitle: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  segment: {
    alignItems: "center",
    borderRadius: 11,
    flex: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 6,
  },
  segmentActive: { backgroundColor: "#7C5CFF" },
  segmentText: { color: "#8A94B2", fontSize: 12, fontWeight: "900" },
  segmentTextActive: { color: "#FFFFFF" },
  segments: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    padding: 4,
  },
  stack: { gap: 16 },
  successMetric: { borderColor: "rgba(52, 211, 153, 0.45)" },
  textArea: { minHeight: 78, paddingTop: 14, textAlignVertical: "top" },
  title: { color: "#E8ECF8", fontSize: 32, fontWeight: "900" },
  warning: { backgroundColor: "rgba(251, 191, 36, 0.14)", color: "#FDE68A" },
  warningMetric: { borderColor: "rgba(251, 191, 36, 0.45)" },
});
