import { StyleSheet } from "react-native";

export const dashboardStyles = StyleSheet.create({
  accentMetric: { borderColor: "rgba(34, 211, 238, 0.45)" },
  actionButton: {
    alignItems: "center",
    borderRadius: 14,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  actionText: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" },
  activeItem: { borderColor: "#7C5CFF" },
  appHeader: {
    alignItems: "center",
    backgroundColor: "#0B0F1A",
    borderBottomColor: "#1E2740",
    borderBottomWidth: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 72,
    paddingHorizontal: 16,
    paddingVertical: 12,
    zIndex: 10,
  },
  appHeaderCollapsed: { minHeight: 58, paddingVertical: 8 },
  avatarButton: {
    alignItems: "center",
    backgroundColor: "#1E2740",
    borderColor: "#253453",
    borderRadius: 18,
    borderWidth: 1,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  avatarText: { color: "#E8ECF8", fontSize: 17, fontWeight: "900" },
  backButton: {
    backgroundColor: "#253453",
    borderRadius: 12,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 14,
  },
  backButtonText: { color: "#E8ECF8", fontSize: 13, fontWeight: "900" },
  badge: {
    backgroundColor: "rgba(138, 148, 178, 0.16)",
    borderRadius: 999,
    color: "#C9D1E8",
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  bottomNav: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderWidth: 1,
    bottom: 18,
    flexDirection: "row",
    gap: 8,
    left: 16,
    padding: 6,
    position: "absolute",
    right: 16,
    shadowColor: "#000000",
    shadowOffset: { height: 14, width: 0 },
    shadowOpacity: 0.34,
    shadowRadius: 24,
    zIndex: 14,
  },
  clearButton: {
    alignItems: "center",
    backgroundColor: "#1E2740",
    borderRadius: 14,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  clearText: { color: "#E8ECF8", fontWeight: "900" },
  completeItem: { borderColor: "rgba(52, 211, 153, 0.4)" },
  checkbox: {
    alignItems: "center",
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 10,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  checkboxText: { color: "#34D399", fontSize: 18, fontWeight: "900" },
  chipRow: { flexDirection: "row", gap: 8, paddingRight: 8 },
  danger: { backgroundColor: "rgba(248, 113, 113, 0.14)", color: "#FECACA" },
  dangerBox: { backgroundColor: "rgba(248, 113, 113, 0.14)" },
  dateButton: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    justifyContent: "center",
    minHeight: 58,
    paddingHorizontal: 14,
  },
  dateClear: {
    alignItems: "center",
    backgroundColor: "#1E2740",
    borderRadius: 14,
    justifyContent: "center",
    minHeight: 58,
    paddingHorizontal: 14,
  },
  dateClearText: { color: "#E8ECF8", fontWeight: "900" },
  dateField: { flexDirection: "row", gap: 10 },
  dateLabel: { color: "#8A94B2", fontSize: 12, fontWeight: "900" },
  datePlaceholder: { color: "#8A94B2", fontSize: 15, fontWeight: "800" },
  dateStack: { gap: 12 },
  dateValue: { color: "#E8ECF8", fontSize: 15, fontWeight: "900" },
  disabledAction: { opacity: 0.45 },
  emptyState: {
    alignItems: "center",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderStyle: "dashed",
    borderWidth: 1,
    gap: 6,
    padding: 20,
  },
  emptyText: { color: "#8A94B2", fontSize: 13, textAlign: "center" },
  emptyTitle: { color: "#C9D1E8", fontSize: 15, fontWeight: "900", textAlign: "center" },
  eyebrow: { color: "#22D3EE", fontSize: 14, fontWeight: "900", marginBottom: 10 },
  flex: { flex: 1 },
  fieldError: {
    backgroundColor: "rgba(248, 113, 113, 0.12)",
    borderColor: "rgba(248, 113, 113, 0.28)",
    borderRadius: 14,
    borderWidth: 1,
    color: "#FECACA",
    fontSize: 13,
    fontWeight: "800",
    lineHeight: 19,
    overflow: "hidden",
    padding: 12,
  },
  filterPanel: { gap: 10 },
  focusCard: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    padding: 16,
  },
  focusLabel: { color: "#22D3EE", fontSize: 12, fontWeight: "900" },
  focusMeta: { color: "#8A94B2", fontSize: 13 },
  focusTitle: { color: "#E8ECF8", fontSize: 19, fontWeight: "900" },
  form: { gap: 12 },
  fab: {
    alignItems: "center",
    backgroundColor: "#7C5CFF",
    borderColor: "rgba(255, 255, 255, 0.2)",
    borderRadius: 999,
    borderWidth: 1,
    bottom: 98,
    height: 48,
    justifyContent: "center",
    position: "absolute",
    right: 20,
    shadowColor: "#000000",
    shadowOffset: { height: 12, width: 0 },
    shadowOpacity: 0.32,
    shadowRadius: 18,
    width: 48,
    zIndex: 16,
  },
  fabText: { color: "#FFFFFF", fontSize: 26, fontWeight: "900", lineHeight: 30 },
  formHint: { color: "#8A94B2", fontSize: 12, fontWeight: "700", marginTop: -4 },
  formHintHidden: { opacity: 0 },
  formLabel: { color: "#C9D1E8", fontSize: 13, fontWeight: "900" },
  headerBrand: { flex: 1, minWidth: 0 },
  headerSubtitle: { color: "#8A94B2", fontSize: 12, fontWeight: "800", marginTop: 2 },
  headerTitle: { color: "#22D3EE", fontSize: 20, fontWeight: "900" },
  hotBadge: { backgroundColor: "rgba(248, 113, 113, 0.16)", color: "#FECACA" },
  inlineActions: {
    borderTopColor: "#1E2740",
    borderTopWidth: 1,
    flexDirection: "row",
    gap: 18,
    paddingTop: 12,
  },
  inlineButton: { justifyContent: "center", minHeight: 44 },
  inlineDanger: { color: "#F87171" },
  inlineText: { color: "#22D3EE", fontWeight: "900" },
  input: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 14,
    borderWidth: 1,
    color: "#E8ECF8",
    fontSize: 15,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  inputDisabled: { opacity: 0.58 },
  item: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  itemBody: { color: "#C9D1E8", fontSize: 14, lineHeight: 20 },
  itemMeta: { color: "#8A94B2", fontSize: 13, fontWeight: "700" },
  itemTitle: { color: "#E8ECF8", fontSize: 17, fontWeight: "900" },
  itemTop: { alignItems: "flex-start", flexDirection: "row", gap: 12 },
  list: { gap: 12 },
  metric: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minWidth: "46%",
    padding: 16,
  },
  metricLabel: { color: "#8A94B2", fontSize: 12, fontWeight: "800", marginBottom: 8 },
  metricValue: { color: "#E8ECF8", fontSize: 30, fontWeight: "900" },
  metricsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  muted: { color: "#8A94B2", flexShrink: 1, fontSize: 13, fontWeight: "700", textAlign: "right" },
  navItem: {
    alignItems: "center",
    borderRadius: 13,
    flex: 1,
    justifyContent: "center",
    minHeight: 48,
  },
  navItemActive: { backgroundColor: "#7C5CFF" },
  navText: { color: "#8A94B2", fontSize: 13, fontWeight: "900" },
  navTextActive: { color: "#FFFFFF" },
  notice: { borderRadius: 14, lineHeight: 20, padding: 13 },
  noticeBox: { borderRadius: 14, gap: 10, padding: 13 },
  noticeTitle: { color: "#FECACA", fontSize: 13, fontWeight: "900" },
  pageButton: {
    alignItems: "center",
    backgroundColor: "#253453",
    borderRadius: 12,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 14,
  },
  pageButtonText: { color: "#E8ECF8", fontSize: 13, fontWeight: "900" },
  pageText: { color: "#8A94B2", fontSize: 13, fontWeight: "900" },
  pagination: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "center",
  },
  panel: {
    backgroundColor: "#121829",
    borderColor: "#1E2740",
    borderRadius: 22,
    borderWidth: 1,
    gap: 14,
    padding: 16,
  },
  primaryAction: { backgroundColor: "#7C5CFF" },
  primaryMetric: { borderColor: "rgba(124, 92, 255, 0.55)" },
  progressFill: { backgroundColor: "#34D399", borderRadius: 999, height: 7 },
  progressText: { color: "#34D399", fontSize: 15, fontWeight: "900" },
  progressTrack: { backgroundColor: "#0B0F1A", borderRadius: 999, height: 7, overflow: "hidden" },
  profileMenu: {
    backgroundColor: "#121829",
    borderColor: "#253453",
    borderRadius: 18,
    borderWidth: 1,
    minWidth: 210,
    padding: 8,
    position: "absolute",
    right: 16,
    shadowColor: "#000000",
    shadowOffset: { height: 16, width: 0 },
    shadowOpacity: 0.32,
    shadowRadius: 24,
    top: 62,
    zIndex: 20,
  },
  profileMenuDanger: { color: "#F87171", fontSize: 14, fontWeight: "900" },
  profileMenuEmail: { color: "#8A94B2", fontSize: 12, fontWeight: "700", marginTop: 2 },
  profileMenuHeader: {
    borderBottomColor: "#1E2740",
    borderBottomWidth: 1,
    marginBottom: 4,
    padding: 10,
  },
  profileMenuItem: { borderRadius: 12, minHeight: 44, paddingHorizontal: 10, paddingVertical: 12 },
  profileMenuItemText: { color: "#E8ECF8", fontSize: 14, fontWeight: "900" },
  profileMenuTitle: { color: "#E8ECF8", fontSize: 14, fontWeight: "900" },
  projectChoice: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  projectChoiceActive: { backgroundColor: "#7C5CFF", borderColor: "#7C5CFF" },
  projectChoiceText: { color: "#C9D1E8", fontSize: 13, fontWeight: "900" },
  projectChoiceTextActive: { color: "#FFFFFF" },
  projectSelector: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  quickActions: { flexDirection: "row", gap: 12 },
  root: { backgroundColor: "#0B0F1A", flex: 1 },
  row: { flexDirection: "row", gap: 10 },
  safeRoot: { backgroundColor: "#0B0F1A", flex: 1 },
  screen: { gap: 16, padding: 16 },
  searchRow: { flexDirection: "row", gap: 10 },
  secondaryAction: { backgroundColor: "#253453" },
  sectionHeading: { color: "#E8ECF8", flex: 1, fontSize: 22, fontWeight: "900" },
  sectionTitle: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  segment: {
    alignItems: "center",
    borderRadius: 11,
    flex: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 6,
  },
  segmentActive: { backgroundColor: "#7C5CFF" },
  segmentText: { color: "#8A94B2", fontSize: 12, fontWeight: "900" },
  segmentTextActive: { color: "#FFFFFF" },
  segments: {
    backgroundColor: "#0B0F1A",
    borderColor: "#253453",
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    padding: 4,
  },
  sheet: {
    backgroundColor: "#121829",
    borderColor: "#253453",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    gap: 14,
    maxHeight: "86%",
    padding: 18,
    paddingBottom: 28,
  },
  sheetBackdrop: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 30,
  },
  sheetScrim: {
    backgroundColor: "rgba(0, 0, 0, 0.52)",
    flex: 1,
  },
  stack: { gap: 16 },
  successMetric: { borderColor: "rgba(52, 211, 153, 0.45)" },
  retryButton: {
    alignItems: "center",
    backgroundColor: "#253453",
    borderRadius: 12,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 16,
  },
  retryText: { color: "#E8ECF8", fontSize: 13, fontWeight: "900" },
  textArea: { minHeight: 78, paddingTop: 14, textAlignVertical: "top" },
  title: { color: "#E8ECF8", fontSize: 32, fontWeight: "900" },
  warning: { backgroundColor: "rgba(251, 191, 36, 0.14)", color: "#FDE68A" },
  warningMetric: { borderColor: "rgba(251, 191, 36, 0.45)" },
});
